"""Learning platform contracts and deterministic Phase 1 helpers."""

from kb_agent.learning.api import LearningApi
from kb_agent.learning.models import (
    Citation,
    DashboardResponse,
    KbStatus,
    LearningContext,
    LearningLesson,
    LearningPathDetail,
    LearningPathSummary,
    NextAction,
    PathProgress,
    ProgressEvent,
    ProgressSummary,
    ProjectSummary,
    Recommendation,
    TopicPage,
    TopicProgress,
    TopicSearchResult,
    TutorRequest,
    TutorResponse,
    UserProgress,
    WarningInfo,
)
from kb_agent.learning.tutor import Tutor, default_tutor_factory

__all__ = [
    "Citation",
    "DashboardResponse",
    "KbStatus",
    "LearningApi",
    "LearningContext",
    "LearningLesson",
    "LearningPathDetail",
    "LearningPathSummary",
    "NextAction",
    "PathProgress",
    "ProgressEvent",
    "ProgressSummary",
    "ProjectSummary",
    "Recommendation",
    "TopicPage",
    "TopicProgress",
    "TopicSearchResult",
    "TutorRequest",
    "TutorResponse",
    "UserProgress",
    "Tutor",
    "default_tutor_factory",
    "WarningInfo",
]
